### ISSUE TITLE
License stanza is deprecated

### ISSUE THREAD

**Issue by justinmayer** [colindean/homebrew-fonts-nonfree#3]
The current `license: commercial` [stanza](https://github.com/colindean/homebrew-fonts-nonfree/blob/master/Casks/font-microsoft-office.rb#L7) is deprecated and produces a warning:

```
Warning: Calling Hbc::DSL#license is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:17:in `block in load'
```

I believe this stanza should be removed.

**Comment by colindean** [comment]
Thank you!
