### ISSUE TITLE
Homebrew Caskroom Change

### ISSUE THREAD

**Issue by mwong10** [colindean/homebrew-fonts-nonfree#7]
The instructions indicate that the command to install the fonts is:

> brew cask install font-microsoft-office

but Homebrew has changed its caskroom command to
> brew install --cask

Thus the command should read:
> brew install --cask font-microsoft-office

**Comment by colindean** [comment]
You're welcome to submit a PR if you can do so before I get to it sometime this evening! Thanks for pointing it out.
