### ISSUE TITLE
font-microsoft-office download failed: 404 not found

### ISSUE THREAD

**Issue by bkleef** [colindean/homebrew-fonts-nonfree#8]
Looks like the ZIP-file is no longer available at URL: https://www.rmtweb.co.uk/wp-content/uploads/2013/06/Calibri-and-Cambria-Fonts.zip.

```sh
brew install font-microsoft-office
==> Caveats
These fonts are copyrighted by Microsoft.
Microsoft UK confirmed you are allowed to have them,
provided that you own a copy of either:
* Microsoft PowerPoint Viewer (free)
* Microsoft Office (Any version, Windows or Mac)
For more information, see https://www.rmtweb.co.uk/calibri-and-cambria-fonts-for-mac.

==> Downloading https://www.rmtweb.co.uk/wp-content/uploads/2013/06/Calibri-and-
curl: (22) The requested URL returned error: 404

Error: Download failed on Cask 'font-microsoft-office' with message: Download failed: https://www.rmtweb.co.uk/wp-content/uploads/2013/06/Calibri-and-Cambria-Fonts.zip
```

**Comment by colindean** [comment]
Looks like the link is now http://static1.squarespace.com/static/61d5ab6bc6583e72b5cf3489/61d5e6c3b1ff8b1bd358ae45/61d5e6cab1ff8b1bd358b1cb/1641408202068/Calibri-and-Cambria-Fonts.zip?format=original

I'll put up a patch today for it unless somebody else beats me to it

**Comment by colindean** [comment]
Looks like that URL isn't working. I'll contact the hoster and see if they have it stored elsewhere. I don't, unfortunately.

**Comment by colindean** [comment]
@rmtweb, could you re-upload that file containing Cambra and Calibri fonts? If not, could you attach it or link to somewhere else here or shoot me an email where I can download it?

**Comment by colindean** [comment]
I've reached out to the hoster via email, too.
